name: Build and Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create .env.production file from template
        run: |
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env.production
          echo "NEXT_PUBLIC_FACEBOOK_URL=${{ secrets.NEXT_PUBLIC_FACEBOOK_URL }}" >> .env.production
          echo "NEXT_PUBLIC_INSTAGRAM_URL=${{ secrets.NEXT_PUBLIC_INSTAGRAM_URL }}" >> .env.production

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/conteudos_espacoeducar:latest

      - name: SSH into server and update
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: githubpages
          key: ${{ secrets.DO_SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/conteudos_espacoeducar:latest
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 --env-file .env.production ${{ secrets.DOCKER_PASSWORD }}/conteudos_espacoeducar:latest
